# Assignment 2 IRS - With Synonyms

Information retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources. The core purpose of this assignment is to give you the flavor of IRS. You need to follow some steps listed below and in the end, you'll be able to build your own small IRS. So, let's start.

In [48]:
# required imports
import numpy as np
import fnmatch
import os


Suppose we have 3 files containing data :

### File Contents

!["This is my book" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f1.png?raw=true)
!["This is my pen" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f2.png?raw=true)
!["This is book is intersting" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f3.png?raw=true)

# Step 1 Create Files with Dummy data

You have to create few files with dummy data of your own choice as shown above.

# Step 2 Traverse Directories

 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [49]:
# Here we have initialized some variables, you can add more if required.

file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set


In [50]:
#Your code starts here   
directory = 'Text files' 

file_count = -1

for filename in os.listdir(directory):
        files_dict[filename] = file_count
        file_count += 1
files_dict = {key: val for key, val in files_dict.items() if val != -1}


print(files_dict)
print(file_count)
#Your code ends here       

{'f1.txt': 0, 'f2.txt': 1, 'f3.txt': 2, 'f4.txt': 3}
4


Displaying the count of files.

In [51]:
print("\nTotal Number  of files\n", file_count)


Total Number  of files
 4


Displaying Dictionary containing all files.

In [52]:
print("\nDictionary containing  files\n", files_dict)


Dictionary containing  files
 {'f1.txt': 0, 'f2.txt': 1, 'f3.txt': 2, 'f4.txt': 3}


# Step 3 Extract Unique Vocabulary

write code to print all the unique words in every file and store them in a set

In [53]:
contents = []
for filename in files_dict:
    with open(os.path.join(directory, filename), 'r') as file:
        file_contents = file.read()
        contents = file_contents.split()
        set(contents)
        unique_word_set = unique_word_set.union(contents)

print("Unique words in every file\n", unique_word_set)

Unique words in every file
 {'my', 'is', 'interesting', 'book', 'smooth', 'This', 'pen'}


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o1.png?raw=true)


# Step 4 Create Term Document Matrix

Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

1. Create Term doc matrix such that colmns will be unique words and all the files will be rows
2. Write code to count all the unique words appearances in all the files and store it in a dictionary for words 

In [54]:
#Your code starts here    
n = len(unique_word_set)
r = len(files_dict)
matrix = [[0] * n for _ in range(r)]

dict_words = {}
j = 0
for i in unique_word_set:
    dict_words[i] = j
    j += 1
print(matrix)
print(dict_words)
#Your code ends here

[[0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0]]
{'my': 0, 'is': 1, 'interesting': 2, 'book': 3, 'smooth': 4, 'This': 5, 'pen': 6}


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o2.png?raw=true)

# Step 5 Fill Term Document Matrix

1. Fill the term doc matrix by checking if the unique word exists in a file or not
2. If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
3. Do the same for all the files present in the directory

In [55]:


def func(directory, filename):
    with open(os.path.join(directory, filename), 'r') as file:
        file_contents = file.read()
    return set(file_contents.split())


for filename, f in files_dict.items():
    words = func(directory, filename)
    for word in words:
        if word in dict_words:
            w = dict_words[word]
            matrix[f][w] = 1

print(matrix)


[[1, 1, 0, 1, 0, 1, 0], [1, 1, 0, 0, 0, 1, 1], [1, 1, 1, 1, 0, 0, 0], [0, 1, 0, 0, 1, 0, 1]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o4.png?raw=true)


# Step 6 Ask for a user Query

For user query make a column vector of length of all the unique words present in a set

In [56]:
#Your code starts here 
data = [0]*n
vctr = np.array(data).reshape(-1, 1)

print(vctr)
#Your code ends here

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o5.png?raw=true)


In [57]:
query = input("\nWrite something for searching:  ")
print("Query is:", query)


Write something for searching:  this is a fascinating publication written with a ballpoint
Query is: this is a fascinating publication written with a ballpoint


### Expected Output

![Expected Output of query](images/Query.png)

# Step 7 Load Synonyms

In [58]:
synonym_file_path = r"files\synonyms.txt"
synonyms_dict = {} # dictionary to store synonyms
#your code starts here


with open(synonym_file_path, 'r') as file:
    for line in file:
        words = line.strip().split(':')
        if len(words) >= 2:
            key = words[0].strip()
            synonyms = [syn.strip() for syn in words[1].split(',')]
            synonyms_dict[key] = synonyms



#your code ends here

print("\nSynonyms Dictionary\n")
synonyms_dict


Synonyms Dictionary



{'write': ['compose', 'draft', 'author', 'create'],
 'file': ['document', 'record', 'dossier', 'report'],
 'example': ['illustration', 'instance', 'sample', 'demonstration'],
 'query': ['question', 'inquiry', 'search', 'request'],
 'synonym': ['equivalent', 'substitute', 'alternate', 'replacement'],
 'retrieve': ['fetch', 'recover', 'obtain', 'bring back'],
 'system': ['framework', 'structure', 'organization', 'arrangement'],
 'search': ['seek', 'look for', 'explore', 'examine'],
 'lost': ['misplaced', 'missing', 'forgotten', 'mislaid'],
 'pen': ['write', 'ink', 'ballpoint', 'fountain'],
 'paper': ['document', 'sheet', 'form', 'letter'],
 'book': ['novel', 'volume', 'publication', 'tome'],
 'read': ['peruse', 'scan', 'study', 'look at'],
 'interesting': ['fascinating', 'engaging', 'intriguing', 'absorbing'],
 'computer': ['machine', 'device', 'processor', 'laptop'],
 'software': ['program', 'application', 'app', 'platform']}

### Expected Output

![Synonym Dict Example](images\Synonym_dict.png)

# Step 8 Extend User Query

In [59]:
expanded_query = []
# Write code to expand the query using synonyms
#your code starts here
def find_keys_by_value(dictionary, target_value):
    keys = []
    for key, values in dictionary.items():
        if target_value in values:
            keys.append(key)
    return keys


query_words = query.split()


keys_for_query_words = []
for word in query_words:
    keys = find_keys_by_value(synonyms_dict, word)
    if keys:
        expanded_query.append(word)
        expanded_query.extend(keys)
    else:
        expanded_query.append(word) 

print("Expanded Query:")
print(expanded_query)

#your code ends here



Expanded Query:
['this', 'is', 'a', 'fascinating', 'interesting', 'publication', 'book', 'written', 'with', 'a', 'ballpoint', 'pen']


### Expected Output

![Extended Query](images\Expanded_Query.png)

Now work with extended query and find the relevant documents.

In [ ]:
# Check every word of query if it exists in the set of unique words or not
# If exists then increment the count of that word in word dictionary


In [60]:
#Your code starts here    

for w in expanded_query:
    if w in unique_word_set:
        a = dict_words[w]  
        vctr[a,:] += 1
print(vctr)
#Your code ends here

[[0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o6.png?raw=true)


# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [61]:
#Your code starts here  
result = np.dot(matrix, vctr)
print(result)
max_value = np.max(result)
max_index = np.argmax(result)

print("Maximum value:", max_value)
print("Index of maximum value:", max_index)

#Your code ends here

[[2]
 [2]
 [3]
 [2]]
Maximum value: 3
Index of maximum value: 2


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o7.png?raw=true)


# Step 8 Display the contents of file


Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [65]:
#Your code starts here
def find_key_by_value(dictionary, value):
    for key, val in dictionary.items():
        if val == value:
            return key
    return None
f = find_key_by_value(files_dict,max_index)
with open(os.path.join(directory, f), 'r') as file:
    print(file.read())


#Your code ends here

my book is interesting


Congratulations Now you are able to build your own small IRS which can work even if query does not have exact same words.